#!/bin/bash
#
#* CDDL HEADER START
#*
#* The contents of this file are subject to the terms of the
#* Common Development and Distribution License, Version 1.0 only
#* (the "License").  You may not use this file except in compliance
#* with the License.
#*
#* You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
#* or http://www.opensolaris.org/os/licensing.
#* See the License for the specific language governing permissions
#* and limitations under the License.
#*
#* When distributing Covered Code, include this CDDL HEADER in each
#* file and include the License file at usr/src/OPENSOLARIS.LICENSE.
#* If applicable, add the following below this CDDL HEADER, with the
#* fields enclosed by brackets "[]" replaced with your own identifying
#* information: Portions Copyright [yyyy] [name of copyright owner]
#*
#* CDDL HEADER END
#*
#*
#* This wrapper has nothing to do with the flash plugin, but simply
#* with as best as possible multi-distro compatibility and gcc/g++ runtime
#* Hence should run on every OpenSolaris/Solaris/Illumos >= snv_130
#* without the need to install any additional gcc/g++ runtime env.
#*
#* Copyright 2015 OpenSXCE.org Martin Bochnig <opensxce@mail.ru>
#* FireFox 20/30/40++ gcc4.x port with Flash support for OpenSolaris++ x86/x64
#*

export LD_LIBRARY_PATH=/usr/lib/firefox43.0b3/lib/firefox-43.0:$LD_LIBRARY_PATH
exec /usr/lib/firefox43.0b3/lib/firefox-43.0/firefox.exe "$@" 
